---
- name: Install haproxy
  apt:
    name: haproxy
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Create cert file for haproxy
  file:
    path: /etc/haproxy/tls-certs/live
    state: directory
    owner: root
    group: root
    mode: 0700


- name: Configure haproxy service
  template:
    src: "{{haproxy_config_template}}"
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0644

- name: Configure haproxy systemd service
  template:
    src: "{{haproxy_service_template}}"
    dest: /etc/systemd/system/haproxy.service.j2
    owner: root
    group: root
    mode: 0644

- name: Enable haproxy
  lineinfile:
    dest: /etc/default/haproxy
    state: present
    regexp: 'ENABLED=0'
    line: 'ENABLED=1'
    owner: root
    group: root
    mode: 0644
  notify: Restart haproxy

